### ISSUE TITLE
Only a maximum of 2 arguments are emited

### ISSUE THREAD

**Issue by dca123** [SupremeTechnopriest/socket.io-mock#16]
### Problem 

When I emit using the mock, only up to two of the arguments provided are emitted. This is because the current setup assumed that the first parameter (payload contains the entire payload). However, [socket io](https://socket.io/docs/v3/server-api/#socket-send-%E2%80%A6args-ack) permits for the payload to be sent via multiple arguments `(socket.emit(eventName[, …args][, ack]))`

For example 
```
socket.on('lobbyTimeout', (...args) => {
    console.log(...args);
});
socket.socketClient.emit(
    'lobbyTimeout',
    10,
    'Brand New Title',
    123
);
```
This outputs 
``` 
10 Brand New Title
```
when the following is expected
```
 10 Brand New Title 123
```

### Fix

I Fixed this issue by changing the emit in socket-client.js to this
```
  emit(eventKey, payload, ack, ...args) {
      if (typeof payload === 'function') {
          payload = null
          ack = payload
      }
      this._socketMock.emitEvent(eventKey, payload, ack, ...args)
  }
```
and the emitEvent in index.js to
```
 emitEvent(eventKey, payload, ack, ...args) {
     if (typeof ack !== 'function' && args.length > 0) {
         this._emitFn(eventKey, payload, ack, ...args)
         return
     }
     this._emitFn(eventKey, createPayload(payload), ack)
 }
```

This might not be the most efficient solution but it fixes my issue for now. For anyone else who might have this same problem, I'm using [patch-package](https://www.npmjs.com/package/patch-package) to patch these changes after install deps

**Comment by SupremeTechnopriest** [comment]
`1.3.2` has been published to npm.  Thanks @Briaoeuidhtns for the fix!
