### ISSUE TITLE
Allow calling as a function

### ISSUE THREAD

**Issue by Pajn** [SupremeTechnopriest/socket.io-mock#2]
Socket IO client is called as a function, see https://github.com/socketio/socket.io-client
For this to be a drop in replacement it should allow to be used in the same way

**Comment by SupremeTechnopriest** [comment]
Sorry for the long delay on this one.  I haven't been using socket.io and honestly forgot about this repo.  I just did some updates to the build and test chains for 2020. Its up as `1.2.4` on npm.

For this, if you still would like to see this happen, could you demonstrate how you would like to use it?  Currently the client of the mock is accessed through the server instance of the mock.

**Comment by Pajn** [comment]
I have since then also migrated away from socket.io because of problems with socket.io itself so I don't need this any more. Thank you!
