### ISSUE TITLE
Disconnect?

### ISSUE THREAD

**Issue by Hyllesen** [SupremeTechnopriest/socket.io-mock#4]
I like the simple API of this package.

But how can I disconnect a client socket? I've tried 

```
    socket.disconnect();
    socket.socketClient.disconnect();
    socket.close();
    socket.socketClient.close();
```

**Comment by Hyllesen** [comment]
I guess I can just use a "disconnect" emit

**Comment by SupremeTechnopriest** [comment]
Hey @Hyllesen.  Its been a while since I've looked at this library.  I ended up abandoning socket.io for raw websockets.  I can add a disconnect for you if that makes life easier.

**Comment by Hyllesen** [comment]
Hey @SupremeTechnopriest it's okay, I think I'm getting by with the disconnect emit! Maybe I'll try and do a PR if I see the need!
