### ISSUE TITLE
error when no message

### ISSUE THREAD

**Issue by prdArioch** [SupremeTechnopriest/socket.io-mock#5]
Error when sending an event without message
ex : socket.socketClient.emit('message');
SyntaxError: Unexpected token u in JSON at position 0
        at JSON.parse (<anonymous>)

can be easily correct with a minor modification

    createPayload = function (e) {
        return (e)?JSON.parse(JSON.stringify(e)):undefined
    },

**Comment by SupremeTechnopriest** [comment]
Thanks for catching this.  Im working on updating this project right now.  This issue will be resolved.

**Comment by SupremeTechnopriest** [comment]
Just updated this repo for 2020.  Also resolved the issue you were seeing here.  You can grab it off npm `1.2.4`.

**Comment by prdArioch** [comment]
thanks for a so fast correction :)
