### ISSUE TITLE
Release isn't tagged

### ISSUE THREAD

**Issue by septagram** [SupremeTechnopriest/socket.io-mock#8]
A small thing, but the latest commits were released as socket.io-mock@1.2.4, but the latest tag is 1.2.3. When next version is release, it won't be as clear which is which.

**Comment by SupremeTechnopriest** [comment]
Looks like I just forgot to tag the release in github.  The latest is on NPM. Ill tag it now.

**Comment by SupremeTechnopriest** [comment]
Should be all set now.  Thanks for the report!
